# ChronoPay Configuration File

# The number of seconds a player must be online for before each payout.
payout-interval: 600

# The number of seconds before a payout cycle resets and players who have reached
# the cap and don't have the bypass permission node can start earning again.
# This value is not affected by /cpreload and requires a full reload of the plugin.
payout-cycle-reset-interval: 86400

# The amount of money to give to each player on every payout.
payout-amount: 0.10

# The maximum amount of money a player can earn per-cycle if they don't have the 'chronopay.bypass.cap' permission node.
payout-cap: 5.0

# The different checks that a player must pass in order to be eligible to earn money.
checks:
  # Checks whether or not multiple players are logged in from the same location.
  # Can be bypassed with the 'chronopay.bypass.address' permission node.
  address: true
  # Checks whether or not a player is AFK (uses Essentials, ignored if Essentials is not present).
  # Can be bypassed with the 'chronopay.bypass.afk' permission node.
  afk: true
  # Checks whether or not a player has reached the configured payout cap for the current payout cycle.
  # Can be bypassed with the 'chronopay.bypass.cap' permission node.
  cap: true

# The messages to display to users in different situations.
# All messages support Minecraft '&' colour codes.
# You can disable any message by leaving it empty or removing the key here.
# Any message that would be displayed to a player in a situation where they
# could have a bypass permission node will not be displayed.
messages:
  # Displayed to a player when they receive a payout.
  # You can use the following macros in this message:
  # {money} - The amount of money payed to the player.
  # {minutes} - The value of payout-interval in minutes.
  # {seconds} - The value of payout-interval in seconds.
  payout: '&7You have received &a{money} &7for {minutes} minutes online time!'
  # Displayed to a player who has reached the payout cap when the current payout cycle resets.
  cycle-reset: '&aYou will now start earning money for activity again!'
  # Displayed to a player when they reach the configured payout cap.
  cap-reached: '&cYou have reached the payout cap for now.'
  # Displayed to a user when they log in if there are already players logged in at their location.
  multiple-accounts: '&cThere are multiple accounts logged in at your location. You will not earn any money.'
  # Displayed to a user when they go AFK.
  gone-afk: '&cYou cannot earn money whilst AFK.'